FROM node:4.2.1
# replace this with your application's default port
EXPOSE 8080

# Expose our web root and log directories log.
VOLUME ["/srv/www"]

# Run app using nodemon
CMD ["node", "/srv/www/server.js"]]
